spring.application.name=microservico-subscriber

server.port=8081
rabbitmq.queuename=MY_TEST_QUEUE

spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.port=8090